# Publish joint states
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

panda_arm_controller:
    type: effort_controllers/JointGroupEffortController
    joints:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7

panda_hand_controller:
    type: effort_controllers/JointGroupEffortController
    joints:
        - panda_finger_joint1
        - panda_finger_joint2
