reach_sim: #namespace

  # Learning General Parameters
  n_actions: 4
  has_object: False
  block_gripper: True
  n_substeps: 20
  gripper_extra_height: 0.2
  target_in_the_air: True
  target_offset: 0.0
  obj_range: 0.15
  target_range: 0.15
  distance_threshold: 0.05
  reward_type: sparse
  init_pos:
    joint0: 1.1
    joint1: 0.0
    joint2: -0.6
    joint3: -1.5
    joint4: 0.0
    joint5: 1.5
    joint6: 0.0